#!/usr/bin/env python

import sys
import time
import random
from euca2ools import Euca2ool

euca_conn = None

def volumes():
    return euca_conn.get_all_volumes([])


max_volume_count = 50
max_launch_count = 4
volume_size = 10

launch_times = {}

def main(test_host):
    try:
        euca = Euca2ool()
        global euca_conn
        euca_conn = euca.make_connection()
    except:
        print "environment variables not configured"
        sys.exit(1)

    loop = 0
    while True:
        vols = volumes()

        # terminate available volumes and check on launched volumes
        for v in vols:
            host = v.status.split(',')[1].strip()
            if test_host and host != test_host:
                continue
            status = v.status.split(' ')[0]
            if status == 'available':
                if launch_times.has_key(v.id):
                    print '%s,%s,%s, %d' % (launch_times[v.id], v.id, host, time.time()-launch_times[v.id])
                    del launch_times[v.id]
                euca_conn.delete_volume(v.id)

        # launching new volumes
        launch_count = min(random.randint(0, max_volume_count-len(vols)), max_launch_count)
        if launch_count > 0:
            for x in range(launch_count):
                if test_host:
                    zone = 'test:%s' % test_host
                else:
                    zone = None
                v = euca_conn.create_volume(size=volume_size, zone=zone)
                launch_times[v.id] = time.time()

        time.sleep(1)


if __name__ == "__main__":
    test_host = None
    if len(sys.argv) > 1:
        test_host = sys.argv[1]
    main(test_host)
